include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    todo: warning
linter:
  rules:
    # = false
    constant_identifier_names: false
    depend_on_referenced_packages: false
    deprecated_member_use_from_same_package: false
    no_default_cases: false
    prefer_foreach: false
    prefer_interpolation_to_compose_strings: false
    sort_constructors_first: false
    use_build_context_synchronously: false # remove it

    # = true
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_empty_else: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_function_literals_in_foreach_calls: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    combinators_ordering: true
    conditional_uri_does_not_exist: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    exhaustive_cases: true
    file_names: true
    implementation_imports: true
    implicit_call_tearoffs: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_annotations: true
    lines_longer_than_80_chars: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_literal_bool_comparisons: true
    no_runtimeType_toString: true #performance
    non_constant_identifier_names: true
    null_check_on_nullable_type_parameter: true
    null_closures: true
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true #performance
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    recursive_getters: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    type_literal_in_constant_pattern: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_late: true # Top-level and static variables with initializers are already evaluated lazily as if they are marked late.
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unreachable_from_main: true
    use_colored_box: true #performance
    use_decorated_box: true #performance
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_super_parameters: true
    use_to_and_as_if_applicable: true
    void_checks: true

    ## Requires code change
    # use_build_context_synchronously: true
    # avoid_dynamic_calls: true
    # unnecessary_lambdas: true
    # avoid_annotating_with_dynamic: true
    # omit_local_variable_types: true
