name: wildr_flutter
description: Wildr Project

publish_to: "none"

#VER_NAME+VER_CODE
#version: 1.7.1+101
#YYYY.MM.DDbb
version: 2023.1215.1+126

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  align_positioned: ^3.0.0
  animated_widgets: ^1.1.0
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.1.0
  adaptive_action_sheet: ^2.0.2
  bloc: ^8.1.2
  blur: ^3.1.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5+4
  country_picker: ^2.0.20
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  debounce_throttle: ^2.0.0
  device_info_plus: ^9.0.3
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  fancy_shimmer_image: ^2.0.3
  firebase_core: ^2.16.0
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_crashlytics: ^3.3.6
  firebase_dynamic_links: ^5.3.6
  firebase_messaging: ^14.6.8
  firebase_performance: ^0.9.2+5
  flavor_config: ^1.3.0
  flutter_app_badger: ^1.5.0
  flutter_bloc: ^8.1.3
  flutter_email_sender: ^6.0.1
  flutter_fgbg: ^0.3.0
  #NetworkImageWithRetry
  flutter_image: ^4.1.6
  flutter_image_compress: ^1.1.3 #Do no upgrade
  flutter_keyboard_size: ^1.0.1
  flutter_overboard: ^3.1.1
  flutter_svg: any
  focused_menu: ^1.0.5
  font_awesome_flutter: ^10.5.0
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.6.0
  google_sign_in: ^6.1.5
  graphql_flutter:
    git:
      url: https://github.com/wildr-inc/wildr-graphql-flutter.git
      ref: development
      path: packages/graphql_flutter
  photo_manager: ^2.7.1
  photo_view: ^0.14.0
  palette_generator: ^0.3.3+2
  http: ^1.1.0
  image_crop: ^0.4.1
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  intl_phone_number_input: ^0.7.3+1
  keyboard_attachable: ^2.1.0
  flutter_keyboard_visibility: ^5.4.1
  loader_overlay: ^2.3.2
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  package_info_plus: ^4.1.0
  page_transition: ^2.0.9
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  preload_page_view: ^0.2.0
  pull_to_refresh: ^2.0.0
  readmore: ^2.2.0
  reorderables: ^0.6.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  timeago: ^3.5.0
  uuid: any
  video_compress: ^3.1.2
  video_player: ^2.7.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.2.2
  flutter_cache_manager: ^3.3.1
  loading_animation_widget: ^1.2.0+4
  connectivity_plus: ^5.0.2
  smooth_page_indicator: ^1.1.0
  lottie: ^2.6.0
  flutter_contacts: ^1.1.7+1
  azlistview: ^2.0.0
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  http_parser: ^4.0.2
  version: ^3.0.2
  store_redirect: ^2.0.1
  flutter_slidable: ^3.0.0
  restart_app: ^1.2.1
  freezed_annotation: ^2.4.1
  syncfusion_flutter_datepicker: ^22.2.9
  syncfusion_flutter_core: ^22.2.9
  combine: ^0.5.6
  helpers: ^1.2.3
  provider: ^6.0.5
  image: ^4.0.17
  collection:
  flutter_sms:
    git:
      url: https://github.com/fluttercommunity/flutter_sms.git
      ref: master
  heroicons: ^0.9.0
  overlay_tooltip: ^0.2.3
  retry: ^3.1.2
  ###Needs upgrade and has breaking changes
  auto_route: ^5.0.4
  flutter_staggered_grid_view: ^0.6.2
  flutter_local_notifications: ^12.0.2
  logger: ^2.0.2+1

#dependency_overrides:
#  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  auto_route_generator: ^5.0.3 #depends on auto_route
  build_runner: ^2.3.3
  flutter_gen_runner:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3 #depends on auto_route_generator
  mocktail: ^1.0.2
  golden_toolkit: ^0.15.0
  bloc_test: ^9.1.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/wildr_logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icon/
    - assets/wildr_verified/
    - assets/wildr_verified/manual_review/smiling/
    - assets/wildr_verified/manual_review/not_smiling/
    - assets/animations/
    - assets/wildr_icons/
    - assets/wildr_icons_png/
    - assets/onboarding/
    - assets/challenges/
    - assets/challenges/onboarding/

  fonts:
    - family: SourceSansPro
      fonts:
        # 200 ExtraLight
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          style: italic
          weight: 200

        #300 Light
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic

        #400 Normal
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          weight: 400
          style: italic

        #500 Medium
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 500
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          weight: 500
          style: italic

        #600 Semi-bold
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic

        #700 Bold
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700

        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic

        #800 Extra Bold
        - asset: assets/fonts/SourceSansPro-Black.ttf
          weight: 800

        - asset: assets/fonts/SourceSansPro-BlackItalic.ttf
          weight: 800
          style: italic

    - family: Mulish
      fonts:
        # 200 ExtraLight
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Mulish-ExtraLightItalic.ttf
          style: italic
          weight: 200

        #300 Light
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-LightItalic.ttf
          weight: 300
          style: italic

        #400 Normal
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 400
        - asset: assets/fonts/Mulish-BlackItalic.ttf
          weight: 400
          style: italic

        #500 Medium
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500

        - asset: assets/fonts/Mulish-MediumItalic.ttf
          weight: 500
          style: italic

        #600 Semi-bold
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-SemiBoldItalic.ttf
          weight: 600
          style: italic

        #700 Bold
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700

        - asset: assets/fonts/Mulish-BoldItalic.ttf
          weight: 700
          style: italic

        #800 Extra Bold
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Mulish-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Nunito
      fonts:
        # 200 ExtraLight
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200

        #300 Light
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic

        #400 Normal
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 400
          style: italic

        #500 Medium
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500

        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic

        #600 Semi-bold
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic

        #700 Bold
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700

        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic

        #800 Extra Bold
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Noto Color Emoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf

    - family: Satoshi
      fonts:
         # 200 ExtraLight
         - asset: assets/fonts/Satoshi/Satoshi-Black.ttf
           weight: 200

         - asset: assets/fonts/Satoshi/Satoshi-BlackItalic.ttf
           style: italic
           weight: 200

         #300 Light
         - asset: assets/fonts/Satoshi/Satoshi-Bold.ttf
           weight: 300
         - asset: assets/fonts/Satoshi/Satoshi-BoldItalic.ttf
           weight: 300
           style: italic

         #400 Normal
         - asset: assets/fonts/Satoshi/Satoshi-Italic.ttf
           weight: 400
           style: italic
         - asset: assets/fonts/Satoshi/Satoshi-Light.ttf
           weight: 400

         #500 Medium
         - asset: assets/fonts/Satoshi/Satoshi-LightItalic.ttf
           weight: 500
           style: italic

         - asset: assets/fonts/Satoshi/Satoshi-Medium.ttf
           weight: 500

         #600 Semi-bold
         - asset: assets/fonts/Satoshi/Satoshi-MediumItalic.ttf
           weight: 600
           style: italic
         - asset: assets/fonts/Satoshi/Satoshi-Regular.ttf
           weight: 600

         #700 Bold
         - asset: assets/fonts/Satoshi/Satoshi-Variable.ttf
           weight: 700

         - asset: assets/fonts/Satoshi/Satoshi-VariableItalic.ttf
           weight: 700
           style: italic

    - family: Inter
      fonts:
        # 200 ExtraLight
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 200

        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 200

        #300 Light
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 300

        #400 Normal
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 400

        #500 Medium
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 500

        #600 Semi-bold
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 600

    - family: SlussenExpanded
      fonts:
        - asset: assets/fonts/slussen/Slussen-Expanded-Semibold.otf

    - family: SlussenExtended
      fonts:
        - asset: assets/fonts/slussen/Slussen-Extended-Regular.otf
