//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Wallet struct {
	ID             string `sql:"primary_key"`
	OwnerID        string
	Balances       string
	Page           string
	FirstEntryDate *time.Time
	LastEntryDate  *time.Time
	Metadata       *string
	Type           int16
	Status         int16
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
