version: 0.0.0
environment: development
debug:
  port: 6060
cache:
  redis:
    addresses:
      server: localhost:6379
  ristretto:
    num_counters: 10000000
    max_cost: 100000000
    buffer_items: 64
sql:
  pg:
    masters:
      - host: localhost
        port: 5432
        user: wildr
        password: wildr
        database: teller_test
        ssl_mode: disable
        max_open_conns: 5
        max_idle_conns: 5
        conn_max_lifetime: 1h
telemetry:
  logger:
    level: info
  tracer:
    host: localhost:4318
token:
  kind: none
transport:
  http:
    port: 8080
    retry:
      timeout: 1s
      attempts: 3
    user_agent: Service http/1.0
  grpc:
    enabled: true
    port: 9090
    security:
      enabled: false
    retry:
      timeout: 1s
      attempts: 3
    user_agent: Service grpc/1.0
migrator:
  path: file://teller/database/migrations
  driver: postgres
health:
  registrations:
    http:
      - name: http
        interval: 10s
        timeout: 1s
        address: https://google.com
    tcp:
      - name: postgres
        interval: 10s
        timeout: 1s
        address: localhost:5432
      - name: redis
        interval: 10s
        timeout: 1s
        address: localhost:6379
model_generator:
  models_path: ./pkg/database/models
