version: 0.2

phases:
  pre_build:
    commands:
      - echo Running migration task
  build:
    commands:
      - TASK_ID=$(aws ecs run-task --launch-type FARGATE --cluster $ECS_CLUSTER --task-definition migration-worker --propagate-tags TASK_DEFINITION --debug --no-paginate --output json --network-configuration "awsvpcConfiguration={subnets=[$MIGRATION_WORKER_SUBNETS],securityGroups=[$MIGRATION_WORKER_SG]}" | jq -r '.tasks[0].taskArn')
      - echo "Migration task created, task id ${TASK_ID}. Waiting..."

  post_build:
    commands:
      - aws ecs wait tasks-stopped --cluster $ECS_CLUSTER --tasks ${TASK_ID}
      - TASK_EXIT_CODE=$(aws ecs describe-tasks --cluster $ECS_CLUSTER --tasks $TASK_ID | jq '.tasks[0].containers[0].exitCode')
      - echo "Migration task done, task id ${TASK_ID}. Exit Code ${TASK_EXIT_CODE}"
      - test $TASK_EXIT_CODE -eq 0 || exit 1

artifacts:
  files:
    - 'output/*'
