CREATE TABLE IF NOT EXISTS wallet (
  id TEXT PRIMARY KEY,
  owner_id TEXT NOT NULL,
  balances JSONB NOT NULL,
  page JSONB NOT NULL,
  first_entry_date TIMESTAMP WITH TIME ZONE,
  last_entry_date TIMESTAMP WITH TIME ZONE,
  metadata JSONB,
  type SMALLINT NOT NULL,
  status SMALLINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
