// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.26.0
// source: teller/pkg/ledger/ledgerentity/ledgerentry/ledgerentry.proto

package ledgerentry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_UNKNOWN_TYPE             Type = 0
	Type_ADS_AWARD                Type = 1
	Type_INVITED_AWARD            Type = 2
	Type_REFERRAL_AWARD           Type = 3
	Type_CONTENT_AWARD            Type = 4
	Type_PROFILE_COMPLETION_AWARD Type = 5
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "ADS_AWARD",
		2: "INVITED_AWARD",
		3: "REFERRAL_AWARD",
		4: "CONTENT_AWARD",
		5: "PROFILE_COMPLETION_AWARD",
	}
	Type_value = map[string]int32{
		"UNKNOWN_TYPE":             0,
		"ADS_AWARD":                1,
		"INVITED_AWARD":            2,
		"REFERRAL_AWARD":           3,
		"CONTENT_AWARD":            4,
		"PROFILE_COMPLETION_AWARD": 5,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_UNKNOWN_STATUS Status = 0
	Status_CREATED        Status = 1
	Status_REVERTED       Status = 2
	Status_FAILED         Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "CREATED",
		2: "REVERTED",
		3: "FAILED",
	}
	Status_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"CREATED":        1,
		"REVERTED":       2,
		"FAILED":         3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescGZIP(), []int{1}
}

type HistoryEvent_FailureDetails_FailureReason int32

const (
	HistoryEvent_FailureDetails_UNKNOWN            HistoryEvent_FailureDetails_FailureReason = 0
	HistoryEvent_FailureDetails_INSUFFICIENT_FUNDS HistoryEvent_FailureDetails_FailureReason = 1
)

// Enum value maps for HistoryEvent_FailureDetails_FailureReason.
var (
	HistoryEvent_FailureDetails_FailureReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "INSUFFICIENT_FUNDS",
	}
	HistoryEvent_FailureDetails_FailureReason_value = map[string]int32{
		"UNKNOWN":            0,
		"INSUFFICIENT_FUNDS": 1,
	}
)

func (x HistoryEvent_FailureDetails_FailureReason) Enum() *HistoryEvent_FailureDetails_FailureReason {
	p := new(HistoryEvent_FailureDetails_FailureReason)
	*p = x
	return p
}

func (x HistoryEvent_FailureDetails_FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryEvent_FailureDetails_FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_enumTypes[2].Descriptor()
}

func (HistoryEvent_FailureDetails_FailureReason) Type() protoreflect.EnumType {
	return &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_enumTypes[2]
}

func (x HistoryEvent_FailureDetails_FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryEvent_FailureDetails_FailureReason.Descriptor instead.
func (HistoryEvent_FailureDetails_FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescGZIP(), []int{1, 0, 0}
}

type Amount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderCurrency    string `protobuf:"bytes,1,opt,name=sender_currency,json=senderCurrency,proto3" json:"sender_currency,omitempty"`
	RecipientCurrency string `protobuf:"bytes,2,opt,name=recipient_currency,json=recipientCurrency,proto3" json:"recipient_currency,omitempty"`
	AmountSent        uint32 `protobuf:"varint,3,opt,name=amount_sent,json=amountSent,proto3" json:"amount_sent,omitempty"`
	ExchangeRate      uint32 `protobuf:"fixed32,5,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
}

func (x *Amount) Reset() {
	*x = Amount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetSenderCurrency() string {
	if x != nil {
		return x.SenderCurrency
	}
	return ""
}

func (x *Amount) GetRecipientCurrency() string {
	if x != nil {
		return x.RecipientCurrency
	}
	return ""
}

func (x *Amount) GetAmountSent() uint32 {
	if x != nil {
		return x.AmountSent
	}
	return 0
}

func (x *Amount) GetExchangeRate() uint32 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

type HistoryEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         Status                       `protobuf:"varint,1,opt,name=Status,proto3,enum=ledgerentry.Status" json:"Status,omitempty"`
	CreatedAt      *timestamppb.Timestamp       `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FailureDetails *HistoryEvent_FailureDetails `protobuf:"bytes,3,opt,name=failure_details,json=failureDetails,proto3" json:"failure_details,omitempty"`
}

func (x *HistoryEvent) Reset() {
	*x = HistoryEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEvent) ProtoMessage() {}

func (x *HistoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEvent.ProtoReflect.Descriptor instead.
func (*HistoryEvent) Descriptor() ([]byte, []int) {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryEvent) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN_STATUS
}

func (x *HistoryEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HistoryEvent) GetFailureDetails() *HistoryEvent_FailureDetails {
	if x != nil {
		return x.FailureDetails
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount         *Amount         `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	IsSender       bool            `protobuf:"varint,2,opt,name=is_sender,json=isSender,proto3" json:"is_sender,omitempty"`
	CounterpartyId string          `protobuf:"bytes,3,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"`
	Type           Type            `protobuf:"varint,4,opt,name=type,proto3,enum=ledgerentry.Type" json:"type,omitempty"`
	Status         Status          `protobuf:"varint,5,opt,name=status,proto3,enum=ledgerentry.Status" json:"status,omitempty"`
	History        []*HistoryEvent `protobuf:"bytes,6,rep,name=history,proto3" json:"history,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Entry) GetIsSender() bool {
	if x != nil {
		return x.IsSender
	}
	return false
}

func (x *Entry) GetCounterpartyId() string {
	if x != nil {
		return x.CounterpartyId
	}
	return ""
}

func (x *Entry) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_UNKNOWN_TYPE
}

func (x *Entry) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN_STATUS
}

func (x *Entry) GetHistory() []*HistoryEvent {
	if x != nil {
		return x.History
	}
	return nil
}

type HistoryEvent_FailureDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason  HistoryEvent_FailureDetails_FailureReason `protobuf:"varint,1,opt,name=reason,proto3,enum=ledgerentry.HistoryEvent_FailureDetails_FailureReason" json:"reason,omitempty"`
	Message string                                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HistoryEvent_FailureDetails) Reset() {
	*x = HistoryEvent_FailureDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryEvent_FailureDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEvent_FailureDetails) ProtoMessage() {}

func (x *HistoryEvent_FailureDetails) ProtoReflect() protoreflect.Message {
	mi := &file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEvent_FailureDetails.ProtoReflect.Descriptor instead.
func (*HistoryEvent_FailureDetails) Descriptor() ([]byte, []int) {
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescGZIP(), []int{1, 0}
}

func (x *HistoryEvent_FailureDetails) GetReason() HistoryEvent_FailureDetails_FailureReason {
	if x != nil {
		return x.Reason
	}
	return HistoryEvent_FailureDetails_UNKNOWN
}

func (x *HistoryEvent_FailureDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto protoreflect.FileDescriptor

var file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x74, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2f, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x1f, 0x0a, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0c, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x61, 0x74, 0x65, 0x22, 0xfc, 0x02, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x51,
	0x0a, 0x0f, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x1a, 0xb0, 0x01, 0x0a, 0x0e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x4e, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x36, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x46,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x34,
	0x0a, 0x0d, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12,
	0x49, 0x4e, 0x53, 0x55, 0x46, 0x46, 0x49, 0x43, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x46, 0x55, 0x4e,
	0x44, 0x53, 0x10, 0x01, 0x22, 0x83, 0x02, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2b,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x73, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2a, 0x7f, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x44, 0x53, 0x5f, 0x41, 0x57, 0x41, 0x52,
	0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x49, 0x54, 0x45, 0x44, 0x5f, 0x41,
	0x57, 0x41, 0x52, 0x44, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x46, 0x45, 0x52, 0x52,
	0x41, 0x4c, 0x5f, 0x41, 0x57, 0x41, 0x52, 0x44, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f,
	0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x57, 0x41, 0x52, 0x44, 0x10, 0x04, 0x12, 0x1c, 0x0a,
	0x18, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x57, 0x41, 0x52, 0x44, 0x10, 0x05, 0x2a, 0x43, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x56, 0x45, 0x52, 0x54,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03,
	0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77,
	0x69, 0x6c, 0x64, 0x72, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x65, 0x6c,
	0x6c, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescOnce sync.Once
	file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescData = file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDesc
)

func file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescGZIP() []byte {
	file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescOnce.Do(func() {
		file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescData = protoimpl.X.CompressGZIP(file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescData)
	})
	return file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDescData
}

var file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_goTypes = []interface{}{
	(Type)(0),   // 0: ledgerentry.Type
	(Status)(0), // 1: ledgerentry.Status
	(HistoryEvent_FailureDetails_FailureReason)(0), // 2: ledgerentry.HistoryEvent.FailureDetails.FailureReason
	(*Amount)(nil),                      // 3: ledgerentry.Amount
	(*HistoryEvent)(nil),                // 4: ledgerentry.HistoryEvent
	(*Entry)(nil),                       // 5: ledgerentry.Entry
	(*HistoryEvent_FailureDetails)(nil), // 6: ledgerentry.HistoryEvent.FailureDetails
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_depIdxs = []int32{
	1, // 0: ledgerentry.HistoryEvent.Status:type_name -> ledgerentry.Status
	7, // 1: ledgerentry.HistoryEvent.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: ledgerentry.HistoryEvent.failure_details:type_name -> ledgerentry.HistoryEvent.FailureDetails
	3, // 3: ledgerentry.Entry.amount:type_name -> ledgerentry.Amount
	0, // 4: ledgerentry.Entry.type:type_name -> ledgerentry.Type
	1, // 5: ledgerentry.Entry.status:type_name -> ledgerentry.Status
	4, // 6: ledgerentry.Entry.history:type_name -> ledgerentry.HistoryEvent
	2, // 7: ledgerentry.HistoryEvent.FailureDetails.reason:type_name -> ledgerentry.HistoryEvent.FailureDetails.FailureReason
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_init() }
func file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_init() {
	if File_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Amount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryEvent_FailureDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_goTypes,
		DependencyIndexes: file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_depIdxs,
		EnumInfos:         file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_enumTypes,
		MessageInfos:      file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_msgTypes,
	}.Build()
	File_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto = out.File
	file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_rawDesc = nil
	file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_goTypes = nil
	file_teller_pkg_ledger_ledgerentity_ledgerentry_ledgerentry_proto_depIdxs = nil
}
