import { Job } from 'bull';

export const JobFake = (overrides: Partial<Job>): Job => ({
  id: '1',
  data: {},
  opts: {},
  attemptsMade: 0,
  processedOn: 0,
  finishedOn: 0,
  queue: {} as any,
  timestamp: 0,
  returnvalue: {},
  log: jest.fn(),
  discard: jest.fn(),
  name: 'job',
  stacktrace: [],
  progress: jest.fn(),
  isCompleted: jest.fn(),
  isFailed: jest.fn(),
  isActive: jest.fn(),
  isDelayed: jest.fn(),
  isWaiting: jest.fn(),
  isPaused: jest.fn(),
  isStuck: jest.fn(),
  getState: jest.fn(),
  update: jest.fn(),
  remove: jest.fn(),
  retry: jest.fn(),
  finished: jest.fn(),
  moveToCompleted: jest.fn(),
  moveToFailed: jest.fn(),
  promote: jest.fn(),
  lockKey: jest.fn(),
  releaseLock: jest.fn(),
  takeLock: jest.fn(),
  toJSON: jest.fn(),
  ...overrides,
});
