-- Active: 1678194366272@@127.0.0.1@5432@wildr
CREATE ROLE wildr WITH LOGIN PASSWORD 'wildr';
ALTER ROLE wildr CREATEDB;
CREATE DATABASE wildr;
GRANT ALL PRIVILEGES ON DATABASE wildr TO wildr;
CREATE DATABASE wildr_test;
GRANT ALL PRIVILEGES ON DATABASE wildr_test TO wildr;
CREATE DATABASE wildr_bi;
GRANT ALL PRIVILEGES ON DATABASE wildr_bi TO wildr;
CREATE DATABASE wildr_bi_test;
GRANT ALL PRIVILEGES ON DATABASE wildr_bi_test TO wildr;